### ISSUE TITLE
no need for killing...

### ISSUE THREAD

**Issue by HeinerTholen** [dgonzal/SFrameBatch#10]
https://github.com/dgonzal/SFrameBatch/blob/development/sframe_batch.py#L180

This line usually produces an exception, because processes can already be done. It's also not needed. `proc.wait()` is enough for keeping everything well in order.

**Comment by dgonzal** [comment]
kind of. every process that is done becomes a zombie for the time that the main program is not finished. will try to solve this monday

**Comment by dgonzal** [comment]
problem persists if one wants to wait for the merging to finish. this is changed to optinional with -c in

 64b25b82d65ee1eeb094dc62c5bedccea6458526
e38e6cc40f36c0ae8c93fbd5c423a77879a537b2

proc.kill() is omitted

**Comment by HeinerTholen** [comment]
Thanks. =)
