### ISSUE TITLE
Empty element (without FileName) in InputData cycle

### ISSUE THREAD

**Issue by dnowatsc** [dgonzal/SFrameBatch#15]
Hi Daniel,
whe I'm working with the latest version of the master branch (so commit 'd231681 print in every loop') and trying to run the following SFrame cycle (https://github.com/dnowatsc/UHH2/blob/pu_reweighting/common/test/PU-Reweighting.xml), sframe_batch splits up the xml file so that in every job, only 8 files are processed, but also adds in each xml file an element containing no filename in the "InputData" cycle (see e.g. in /nfs/dust/cms/user/nowatsd/sFrameNew/RunII-25ns-v2/CMSSW_7_4_15_patch1/src/UHH2/PUHistogram/workdir/TTbar_1.xml). This makes SFrame crash with the error message "workdir/TTbar_100.xml:25: element In: validity error : Element In does not carry attribute FileName
<In Lumi="0.0"/>"
Do you know why this empty element is always added and how to avoid that?
Cheers,
Dominik

**Comment by dgonzal** [comment]
Hi Dominik, 

FileSplit was designed to have always an Output Tree, I will fix it. The Input Tree has to be second last and the Output Tree last in  InputData. 

Cheers 

Daniel

**Comment by dgonzal** [comment]
Just updated the code. Now it hopefully works correctly. Will let the issue for tomorrow open if you happen to find it not working or.

**Comment by dnowatsc** [comment]
Hi,
I tested it again with the new version and the config files now look fine (see e.g. /nfs/dust/cms/user/nowatsd/sFrameNew/RunII-25ns-v2/CMSSW_7_4_15_patch1/src/UHH2/PUHistogram-test/workdir/TTbar_100.xml). I didn't submit the jobs to the grid though but now it should work, thanks.
