### ISSUE TITLE
AutoResubmit failure

### ISSUE THREAD

**Issue by HeinerTholen** [dgonzal/SFrameBatch#23]
I've got an error on the development branch:

sframe_batch.py VLQSemiLepPreSel.xml 
workdir has been created
filling manager
Splitting job by files Run2015D_Mu
Traceback (most recent call last):
  File "/nfs/dust/cms/user/tholenhe/installs/bin/sframe_batch.py", line 101, in <module>
    manager.process_jobs(cycle.Cycle_InputData,Job)
  File "/afs/desy.de/user/t/tholenhe/dev/SFrameBatch/Manager.py", line 119, in process_jobs
    self.subInfo[process].resubmit = header.AutoResubmit #Reset the retries every time you start
AttributeError: type object 'header' has no attribute 'AutoResubmit'

These are my config lines:
   <ConfigParse NEventsBreak="0" FileSplit="8" AutoResubmit="0"/>
   <ConfigSGE RAM="2" DISK="2" Mail="heiner@cern.de" Notification="as" Workdir="workdir"/>

Probably you're about to fix it, I'll use the master branch in the meantime.. =)

**Comment by dgonzal** [comment]
yes new patches are rolling out
