### ISSUE TITLE
error submitting jobs 

### ISSUE THREAD

**Issue by IreneZoi** [dgonzal/SFrameBatch#37]
Hi!
I'm having an error submitting some jobs, similar to https://github.com/dgonzal/SFrameBatch/issues/33

This is the error:

$ sframe_batch.py config/VBFresonanceToWW_PUPPI_data_JetHt2016B.xml
workdir_data_B has been created
starting manager
DATA_JetHT_Run2016B: 133751692 events
 Result.xml created for further jobs
--------------------------------------------------------------------------------
Status of files
                   Sample Name:  Ready #Files [%]
           DATA_JetHT_Run2016B:      0   1672 000  Working 
Number of files:  0 / 1672 (100) / /
================================================================================
SFrame Batch was running for 1837.3 sec

$ sframe_batch.py -s config/VBFresonanceToWW_PUPPI_data_JetHt2016B.xml
starting manager
Using saved settings from: workdir_data_B/SubmissinInfoSave.p
Found Submission Info for DATA_JetHT_Run2016B
 Result.xml created for further jobs
workdir_data_B/Stream_DATA_JetHT_Run2016B has been created
Traceback (most recent call last):
  File "/nfs/dust/cms/user/zoiirene/SFrameBatch/sframe_batch.py", line 224, in <module>
    status = SFrameBatchMain(sys.argv[1:])
  File "/nfs/dust/cms/user/zoiirene/SFrameBatch/sframe_batch.py", line 185, in SFrameBatchMain
    if options.submit: manager.submit_jobs(cycle.OutputDirectory,nameOfCycle)
  File "/nfs/dust/cms/user/zoiirene/SFrameBatch/Manager.py", line 156, in submit_jobs
    process.arrayPid = submit_qsub(process.numberOfFiles,self.outputstream+str(process.name),str(process.name),self.workdir)
  File "/nfs/dust/cms/user/zoiirene/SFrameBatch/batch_classes.py", line 79, in submit_qsub
    return (proc_qstat.communicate()[0].split()[2]).split('.')[0]
IndexError: list index out of range

If someone could help me understanding and fixing the issue would be great. Thank you!
Best,
Irene

**Comment by dgonzal** [comment]
I'm very sorry that I didn't see the error bug report! 
If I do not answer pls contact me also personally. 
This looks like something was broken in the workdir and removing that could have solved it.
I guess this is very outdated, and I will close this comment

**Comment by IreneZoi** [comment]
I think it happened when you were at boost conference, so this is why I didn't write you.
Don't worry and thanks!
